### ISSUE TITLE
Search / filter issue

### ISSUE THREAD

**Issue by amyflo** [amyflo/censussurveys#17]
Cant search and filter at the same time! Look into how the search toggle and the filter is working. The filter function is showing when the .class is selected and hiding all cards. The search is toggling in the cards themselves. Need to find a way to build it so that the input is passed in as a value? 

Another thing to consider is the checkbox on change. When a new checkbox is checked, what happens to the function? So either on keyup or on change there needs to be a function that can handle both requests!

**Comment by loganpowell** [comment]
Do you want an extra pair of eyes on it?

**Comment by amyflo** [comment]
Airtable API is not showing up on GitHub Pages -- look into it even tho call works on live server on desktop
